onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  cookie: ^1.0.2
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
